[project]
name = "metadata-check"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonschema>=4.25.1",
    "pyarrow>=22.0.0",
    "pyyaml>=6.0.3",
]
